In [12]:
import pandas as pd
import numpy as np

In [10]:
# =============================================
# ========  Uncomment jika diperlukan  ========
# =============================================

# df_s1_totaltime = pd.read_csv(r"..\data\sesi1\TPS fulltank - S1 - Total Waktu.csv")
# df_s1_itrarrival = pd.read_csv(r"..\data\sesi1\TPS fulltank - S1 - Inter Arrival.csv")

# df_s2_servtime = pd.read_csv(r"..\data\sesi2\TPS fulltank - S2 - Waktu Pelayanan.csv")
# df_s2_que = pd.read_csv(r"..\data\sesi2\TPS fulltank - S2 - Antrian.csv")
# df_s2_quetime = pd.read_csv(r"..\data\sesi2\TPS fulltank - S2 - Waktu Mengantri.csv")
# df_s2_totaltime = pd.read_csv(r"..\data\sesi2\TPS fulltank - S2 - Waktu Total.csv")
# df_s2_itrarrival = pd.read_csv(r"..\data\sesi2\TPS fulltank - S2 - InterArrival.csv")

# df_s3_servtime = pd.read_csv(r"..\data\sesi3\TPS fulltank - S3 - Waktu Pelayanan.csv")
# df_s3_que = pd.read_csv(r"..\data\sesi3\TPS fulltank - S3 - Panjang Antrian.csv")
# df_s3_quetime = pd.read_csv(r"..\data\sesi3\TPS fulltank - S3 - Waktu Mengantri.csv")
# df_s3_totaltime = pd.read_csv(r"..\data\sesi3\TPS fulltank - S3 - Total Waktu.csv")
# df_s3_itrarrival = pd.read_csv(r"..\data\sesi3\TPS fulltank - S3 - Interarrival.csv")

# df_s4_servtime = pd.read_csv(r"..\data\sesi4\TPS fulltank - S4 - Waktu Pelayanan.csv")
# df_s4_que = pd.read_csv(r"..\data\sesi4\TPS fulltank - S4 - Panjang Antrian.csv")
# df_s4_quetime = pd.read_csv(r"..\data\sesi4\TPS fulltank - S4 - Waktu Mengantri.csv")
# df_s4_totaltime = pd.read_csv(r"..\data\sesi4\TPS fulltank - S4 - Waktu Total.csv")
# df_s4_itrarrival = pd.read_csv(r"..\data\sesi4\TPS fulltank - S4 - Interarrival.csv")

df_rekap = pd.read_csv(r"..\data\TPS fulltank - Rekap.csv")

In [22]:
df_rekap

,Sesi,Rerata Waktu Pelayanan (s),Rerata Panjang Antrean (s),Rerata Waktu Mengantri (s),Rerata Waktu Total (s),Interarrival Time (s),Jumlah Nozzle Aktif
0,Pertama,-,-,-,100.87,101.43,1
1,Kedua,50.42,6,264.50,368.50,52.00,1
2,Ketiga,55.05,11.92307692,515.24,644.57,51.13,1
3,Keempat,46.79,6.333333333,299.39,443.81,44.13,1

Used Parameter:
<br>
$\lambda =$ Arrival Rate $= \
{1}{\text{rata-rata interarrival time}}$
<br>
$\mu =$ Service Rate
<br>
$\rho =$ Utilization $= \frac{\lambda}{c \times \mu}$
<br>
$Lq =$ Length of Queue
<br>
$Wq =$ Waiting time in Queue

In [21]:
df_rekap_nodash = df_rekap.replace('-', np.nan)

avg_itrarrival = df_rekap_nodash['Interarrival Time (s)'].astype(float)
nozzle_count = df_rekap_nodash['Jumlah Nozzle Aktif'].astype(float)

session = df_rekap_nodash['Sesi']
arrival_rate = 1/avg_itrarrival
service_rate = df_rekap_nodash['Rerata Waktu Pelayanan (s)'].astype(float)
utilization = arrival_rate/(nozzle_count*service_rate)
Lq = df_rekap_nodash['Rerata Panjang Antrean (s)'].astype(float)
Wq = df_rekap_nodash['Rerata Waktu Mengantri (s)'].astype(float)

df_parameters = pd.DataFrame([session, arrival_rate, service_rate, utilization, Lq, Wq])
df_parameters = pd.DataFrame({
    'Sesi': df_rekap_nodash['Sesi'],
    'λ (Lambda)': arrival_rate,
    'μ (Mu)': service_rate,          
    'ρ (Rho)': utilization,                 
    'Lq': df_rekap_nodash['Rerata Panjang Antrean (s)'],
    'Wq': df_rekap_nodash['Rerata Waktu Mengantri (s)']
})
df_parameters

      Sesi  λ (Lambda)  μ (Mu)   ρ (Rho)           Lq      Wq
0  Pertama    0.009859     NaN       NaN          NaN     NaN
1    Kedua    0.019231   50.42  0.000381            6  264.50
2   Ketiga    0.019558   55.05  0.000355  11.92307692  515.24
3  Keempat    0.022660   46.79  0.000484  6.333333333  299.39